### ISSUE TITLE
issues with Process_hybrid tools and the documentation

### ISSUE THREAD

**Issue by ZCWang95** [tbohn/NLCD_INEGI#1]
1. "mix" comment in the example $LU_CODES_TABLE file
The "process_urban_lu_map.pl" script uses "mix" to identify those class codes that need to be replaced with NLCD_INEGI class codes. However, the example $LU_CODES_TABLE file uses "mixed" , which might be misleading to users.

2. wrong column number
The "process_urban_lu_map.pl" reads column 3 of the $LU_CODES_TABLE file to decide if the class needs to be replaced or not. However, the example $LU_CODES_TABLE file puts the "nulled"/"mix" comment in the 4th column. Thus, the $fields[2] should be changed to $fields[3] in line 37, 40 and 43. 

3. file name rule of the "$LAND_USE_FILE" 
The first argument read by the "process_urban_lu_map.pl" script ("$LAND_USE_FILE" ) needs to be end with ".resolution_deg.asc". It'd better to specify this in the documentation file.

**Comment by tbohn** [comment]
Thanks for catching these bugs, Zhaocheng.  I've addressed them with commit b67ee8e41657795ac99f553c0623479238d121bd
